// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Track struct {
	TrackKey   string
	Artist     string
	Title      string
	Album      string
	DurationMs int64
	FileID     sql.NullString
	LocalPath  sql.NullString
	CreatedAt  int64
	LastUsedAt int64
}
