// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const clearLocalPath = `-- name: ClearLocalPath :exec
UPDATE tracks SET local_path = NULL WHERE track_key = ?
`

func (q *Queries) ClearLocalPath(ctx context.Context, trackKey string) error {
	_, err := q.db.ExecContext(ctx, clearLocalPath, trackKey)
	return err
}

const getTrack = `-- name: GetTrack :one
SELECT track_key, artist, title, album, duration_ms, file_id, local_path, created_at, last_used_at
FROM tracks
WHERE track_key = ?
`

func (q *Queries) GetTrack(ctx context.Context, trackKey string) (Track, error) {
	row := q.db.QueryRowContext(ctx, getTrack, trackKey)
	var i Track
	err := row.Scan(
		&i.TrackKey,
		&i.Artist,
		&i.Title,
		&i.Album,
		&i.DurationMs,
		&i.FileID,
		&i.LocalPath,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listLRUCandidates = `-- name: ListLRUCandidates :many
SELECT track_key, local_path
FROM tracks
WHERE local_path IS NOT NULL
ORDER BY last_used_at ASC
LIMIT ?
`

type ListLRUCandidatesRow struct {
	TrackKey  string
	LocalPath sql.NullString
}

func (q *Queries) ListLRUCandidates(ctx context.Context, limit int64) ([]ListLRUCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLRUCandidates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLRUCandidatesRow
	for rows.Next() {
		var i ListLRUCandidatesRow
		if err := rows.Scan(&i.TrackKey, &i.LocalPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchLastUsed = `-- name: TouchLastUsed :exec
UPDATE tracks SET last_used_at = ? WHERE track_key = ?
`

type TouchLastUsedParams struct {
	LastUsedAt int64
	TrackKey   string
}

func (q *Queries) TouchLastUsed(ctx context.Context, arg TouchLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchLastUsed, arg.LastUsedAt, arg.TrackKey)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO tracks (
  track_key, artist, title, album, duration_ms, file_id, local_path, created_at, last_used_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(track_key) DO UPDATE SET
  artist       = excluded.artist,
  title        = excluded.title,
  album        = excluded.album,
  duration_ms  = excluded.duration_ms,
  file_id      = COALESCE(excluded.file_id, tracks.file_id),
  local_path   = COALESCE(excluded.local_path, tracks.local_path),
  last_used_at = excluded.last_used_at
`

type UpsertTrackParams struct {
	TrackKey   string
	Artist     string
	Title      string
	Album      string
	DurationMs int64
	FileID     sql.NullString
	LocalPath  sql.NullString
	CreatedAt  int64
	LastUsedAt int64
}

func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.TrackKey,
		arg.Artist,
		arg.Title,
		arg.Album,
		arg.DurationMs,
		arg.FileID,
		arg.LocalPath,
		arg.CreatedAt,
		arg.LastUsedAt,
	)
	return err
}
